# Generated by Django 4.1.6 on 2023-02-09 01:48

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True, editable=False, max_length=22
            ),
        ),
    ]
