# Generated by Django 4.1.6 on 2023-02-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="thumbnails/skills/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
