# Generated by Django 4.1.6 on 2023-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="barcode",
        ),
        migrations.AddField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="tickets/qr_code"),
        ),
    ]
