# Generated by Django 4.1.6 on 2023-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_remove_ticket_barcode_ticket_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
