# Generated by Django 4.1.6 on 2023-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_ticket_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
